### ISSUE TITLE
Design refactor

### ISSUE THREAD

**Issue by lordblendi** [bme-db-lab/szglab5-frontend#1]
- responsive design
- uj szinek, esetleg betutipus valasztasa

**Comment by csutorasr** [comment]
40eeb845871dd5daf48dc68178976da38448930c commitban a responsive design megcsinálva.

**Comment by lordblendi** [comment]
Meg a szineket meg kellene valtoztatni, ha lehetseges. Valami egyseges hatterszin, esetleg szurke. Kerlek kovesd az arculati kezikonyvet: http://www.vik.bme.hu/page/523/

**Comment by lordblendi** [comment]
Jo lett a reszponziv design! https://db.bme.hu/~szepes/ frissitve :)

**Comment by csutorasr** [comment]
A szinek is megcsinalva.
