### ISSUE TITLE
Javito - javitas/kijavitott feladatok

### ISSUE THREAD

**Issue by lordblendi** [bme-db-lab/szglab5-frontend#100]
Jo lenne egy szuro a feladattipusra is (22-auto/23-hajo).

**Comment by jmarton** [comment]
Javítandónál van feladattípus szűrő, a kijavítottaknál TODO.

**Comment by csutorasr** [comment]
@Kisfejes A backend ezt tamogatja?

**Comment by jmarton** [comment]
superseded by #138
