### ISSUE TITLE
Keres folyamatosan pending-el

### ISSUE THREAD

**Issue by lordblendi** [bme-db-lab/szglab5-frontend#102]
Olyan bugot talaltam, hogy javitokent:
1. megnyitok ertekelesre egy hallgatot
2. lezajlik az ertekeles, kb 10 perc, egyik tabon nyitva a fecske, masikon akep
3. beirom a jegyet
4. veglegesitem. Latom is, hogy sikeres, megjelenik alul a zold teglalap. 
5. Oldal tetejen vissza gomb (szoval nem bongeszo vissza)
6. kivalasztok egy masik hallgatot
7. ugyanugy lezajlik az ertekeles
8. beirom a jegyet, veglegesitem, es a szervertol nem erkezik valasz. ebbol ugye frontenden semmi se latszodik, de developer toolsban latszodott, hogy folyamatosan pendinggel

Egyelore meg nem sikerult varakozassal eredmenyt kicsikarnom, ilyenkor ctrl-f5 es utana megy a jegybeiras ujra 1 hallgatora. A hiba windows es linux chrome-ban jott elo, mashol nem probaltam. A kov heten, amikor megint javitok, majd megprobalok nem elfelejteni kepernyokepet/felvetelt kesziteni.

@Kisfejes Az 5-10 perc inaktivsag okozhat ilyet backend reszrol? Mert gondolom be van allitva egy session timeout, amiutan en azt varnam el, hogy kijelentkeztet a rendszer es nem pedig azt, hogy reload segit rajta.

**Comment by Kisfejes** [comment]
Az inaktivitas szerintem nem okozhat ilyet, ha le is jar a token, akkor 403-as valaszt kuld a szerver. Tudom valahogy reprodukalni a hibat fejlesztoi kornyezetben?

**Comment by lordblendi** [comment]
Probald meg a fent leirt lepeseket megismetelni.

**Comment by Kisfejes** [comment]
AKEP nelkul vegigmentem a pontokon, de nem sikerult reprodukalnom (nem tudom mennyire kulcsfontossagu, hogy mellette meg van nyitva az AKEP). Neked mindig elojon? Esetleg ha legkozelebb elojon, akkor egy korulbeli timestampet ha tudsz mondani, akkor korulneznek a log-ban, hatha latok valamit.

Jo lenne utanajarni, az hogy a szerver nem valaszol a http keresre eleg nagy bug.

**Comment by lordblendi** [comment]
Rendben, a heten valoszinuleg javitok meg legkorabban szerdan, akkor majd kuldok timestampet es HAR log-ot is.

**Comment by lordblendi** [comment]
@szaszm megoldasa ota nem lattam ezt a hibat.
