### ISSUE TITLE
Demonstrátor - pótlabor elkülönítése a normál laboroktól

### ISSUE THREAD

**Issue by jmarton** [bme-db-lab/szglab5-frontend#105]
A pórmérést vezető demonstrátor egyben látja az adott labortípus normál és pótló névsorát.

A helyzet mögött az áll, hogy a frontend a demonstrátor lapján az `EventTemplate` egyedeket (méréstípus) listázza a menüben, noha a demonstrátor által vezetett laboralkalmakat (időpont+labortípust) kellene listázni.

A jelenlegi viselkedés feltehetőleg akkor is gondot okozna, ha egy demonstrátornak több csoportja lenne: ezesetben egy névsorban szerepelne az összes csoportjának a hallgatója, és még a feladatsor generálás is egyszerre történne.

A mellékelt ábrán az SQL2 labor demonstrátori nézetének részlete látható, a szürke cikk-cakkos vonalnál csökkentve a névsor hosszát. Az ábrán zölddel jelöltem a normál laborra vonatkoró információt és feladatlap generáló gombot, pirossal pedig a pótlásra vonatkozókat.

![demonstrator-potlabor](https://user-images.githubusercontent.com/10688599/34907075-430cefce-f879-11e7-9e7c-00d6806de545.jpg)

**Comment by lordblendi** [comment]
Amennyiben külön csoportként lesznek felvéve a pótlaborok, akkor a https://github.com/bme-db-lab/szglab5-frontend/pull/127 megoldja ezt a problémát. A csoport felosztása jelenleg a event.StudentRegistration.neptunCourseCode alapján megy.

**Comment by lordblendi** [comment]
Előző hozzászólás frissítve:

Amennyiben külön csoportként lesznek felvéve a pótlaborok, akkor a https://github.com/bme-db-lab/szglab5-frontend/pull/127 megoldja ezt a problémát. Ebben az esetben le is vehetnénk a pót táblázatot.

A feladatsor generálás gomb nem működik csoport specifikusan, így az mindenkinek egyszerre legenerál mindent.

Én még azt is javasonlnám amúgy, hogy a pótlabor külön jelenjen meg bal oldalt (külön event template lenne?)
