### ISSUE TITLE
IE10 kompatibilitas

### ISSUE THREAD

**Issue by lordblendi** [bme-db-lab/szglab5-frontend#107]
A frontend mukodjon IE10-en is, de kozben maradjon reszponziv.

**Comment by jmarton** [comment]
@gajdos tudnál screenshotot mutatni, hogy pl. hol és mi a gond IE10-en?

**Comment by gajdos** [comment]
Nem egykönnyen, ugyanis ha valami kiderült, Nóri ezeket röptében meggyógyította. Egyébként sem gondolnám, hogy a témára sok energiát érdemes szánni. Az úgy nem műküdhet, hogy jelzem, ha valami szerintem nem OK?

**Comment by lordblendi** [comment]
@gajdos Nekem ok. En csak arra emlekszem, hogy azt mondtad, hogy IE10-en szetesik teljesen, ezert chrome-ot hasznalsz. De ez honapokkal ezelott volt.

**Comment by lordblendi** [comment]
@gajdos Akkor mar nem igy nez ki IE10-en? Nem remlik, hogy ezzel egyebkent foglalkoztam volna. Ezeket 2017. oktober 14-en kuldted nekem Skype-on.

![la ie10 full screeen](https://user-images.githubusercontent.com/1140416/35242104-ef8d9b86-ffb8-11e7-8f91-90b413ef0e53.png)
![la ie10](https://user-images.githubusercontent.com/1140416/35242105-efa76b42-ffb8-11e7-9b4d-a775c07c49f8.png)

**Comment by lordblendi** [comment]
Beszeltem Sandorral, nem fogjuk ezt tamogatni. Most ugy sem prioros es minel tovabb halogatjuk, annal inkabb folosleges ra idot szanni.
