### ISSUE TITLE
Javító nem lejárt határidejű JK-t ne lásson

### ISSUE THREAD

**Issue by jmarton** [bme-db-lab/szglab5-frontend#108]
Javitó csak akkor lássa a *javítandó kiválasztása* listában a jegyzőkönyvet, ha annak lejárt a beadási határideje.

Forrás: bme-db-lab/szglab5-main#1

*szerk:* szöveg egyértelműsítve, 2018-01-22, jmarton

**Comment by lordblendi** [comment]
Hogy erted, hogy a `nem véglegesített jegyzokonyveknek nem kellene megjelenniuk`? A javitonak, aki javitja? A nem lejart hatarideju jegyzokonyvek nem jelennek meg jelenleg a javitoknal.

**Comment by csutorasr** [comment]
Ez nem frontend hiba. A frontenden is lehet javitani, de a jsonapi hivasaval biztonsagi res lenne, ha le lehetne foglalni.

**Comment by lordblendi** [comment]
Nem ertem, hogy milyen hibarol beszelsz. Emlekeim szerint ugy mukodik, ahogy kellene: nem mutatja a nem lejart hatarideju jegyzokonyveket.

**Comment by csutorasr** [comment]
En azt nem ellenoriztem, hogy el-e a dolog, csak leirtam, hogy ennek egyebkent sem itt lenne a helye.

Ha frontenden nincs ilyen, akkor zard le kerlek.

**Comment by jmarton** [comment]
ez valószínűleg meg van oldva, mert a frontend küld `isOver=true` paramétert, és a backend látszólag feldolgozza: https://github.com/bme-db-lab/szglab5-backend/blob/master/endpoints/deliverables/list.js#L50

**Comment by lordblendi** [comment]
@jmarton Ellenőriztem, úgy tűnik működik.
