### ISSUE TITLE
Nem véglegesített értékelések megkülönböztetése

### ISSUE THREAD

**Issue by jmarton** [bme-db-lab/szglab5-frontend#109]
Latszodjon a laborvezeto (de nem a hallgató!) szamara a nem veglegesitett jkv ertekeles, de jól észrevehető legyen, hogy azon az értékelésen még dolgozik a javító.

A regi rendszerben ezt nem lehet megkulonboztetni, igy nem vegleges ertekelesre kapott par hallgato jegyet az elmult evekben.

Forrás: bme-db-lab/szglab5-main#1

**Comment by csutorasr** [comment]
Miert latszodjon a felkesz ertekeles? Sokkal biztonsagosabb, ha csak a teljesen kesz ertekelest lathatja csak, elotte fel informaciok feleslegesek. Tudsz olyan use-case-t, ahol ez elofodulhat, hogy hasznos?

**Comment by jmarton** [comment]
Ehhez kapcsolódóan a demonstrátornál egy hallgató értékelése lapon a véglegesítve toggle button elhelyezkedése javítandó annak érdekében, hogy egyértelmű legyen, mihez tartozik. Az alábbi képen a beugró véglegesítve toggle-ja látható, de az elrendezés azt sugallja, hogy az a jegyzőkönyv értékelésre vonatkozik.

![kép](https://user-images.githubusercontent.com/10688599/94986962-3be9a080-0563-11eb-8bd0-97549993af0f.png)

**Comment by lordblendi** [comment]
És akkor a vonal alá rakok majd egy mezőt, ami leírja, hogy a jegyzőkönyv értékelése végleges-e.

**Comment by lordblendi** [comment]
Józsival megbeszélve a megkülönböztetéshez inkább a következőt használjuk:
- piros border körbe, ha nem végleges
- piros felirat, hogy végleges-e

**Comment by lordblendi** [comment]
Nincs véglegesítve:
![image](https://user-images.githubusercontent.com/1140416/94993250-eaa3d600-058f-11eb-8ea8-717c93ed5675.png)

Véglegesítve van:
![image](https://user-images.githubusercontent.com/1140416/94993264-fc857900-058f-11eb-9b68-d16d4d593ea5.png)
