### ISSUE TITLE
Böngésző „vissza” funkciójának konzisztens kezelése

### ISSUE THREAD

**Issue by dnet** [bme-db-lab/szglab5-frontend#113]
A böngésző „vissza” funkciójától tipikusan azt várja egy felhasználó, hogy a navigálási események által mélyített veremből egyesével visszahozza az előző állapotokat. AJAX esetén ez érdekes kérdés, viszont számomra zavaró, hogy a frontend ezt hol megvalósítja, hol nem, és az inkonzisztens viselkedés frusztrál. Nem véletlenül hívom végig, következetesen funkciónak és nem gombnak, mivel én például billentyűzettel gyorsan tudok dolgozni, így reflexből `Alt` + `<-` kombinációt nyomok, ha vissza akarok jutni, és nem az egérrel keresgélem meg, hogy az _n_ szintű struktúrában pontosan a képernyő mely pontjára kattintva lehet visszajutni az előző helyre.

A jelek szerint a frontenden a funkciók között működik, így ha belépés után például a beállításokra dob be, majd átmegyek a demonstrátori funkcióba, a „vissza” funkció a beállításokhoz visz. Azonban ha kiválasztom mondjuk a Oracle labort, majd átkattintok az SQL laborra, a „vissza” funkció nem az Oracle laborra visz, hanem a beállítások közé. Ez még zavaróbb, ha megnyitok egy hallgatót egy mérésen belül, majd reflexből „vissza” funkciót hívok, mert ilyenkor ismét a beállításokhoz jutok, szóval innentől kezdhetem újra a több lépéses navigációt (Demonstrátor -> labor kiválasztása -> másik hallgató kiválasztása).

A kérésem tehát: legyen konzisztens a böngészőbe épített „vissza” funkció működése, beleértve a demonstrátor modul laborjait és hallgatóit (legutóbbi laborhoz menjen vissza).

**Comment by csutorasr** [comment]
1. Megoldás:
Route-ok felvétele szinte minden egyes componenshez, majd az adatok egy részét routeparamtéren és modellen, maradék részét (ha marad ilyen) service-ken keresztül kell átküldeni a komponensnek. A nézetváltásoknál változók létezése helyett a router outletet kell használni a nézetek cseréjére. (pl: default route a választó komponens, :id paraméterű a részletes nézet.)

A szűrők és egyéb választók értékeit is el kell menteni a tökéletes implementáláshoz, de így 3 gyors vissza a keresés előtti részre nagyon leterhelné a backendet, így ezt kihagynám.

Másik megoldás a vissza esemény felüldefiniálása, de ezt nem ajánlom.

**Comment by lordblendi** [comment]
> Route-ok felvétele szinte minden egyes componenshez

Ez azert tulzas. [Nested routinggal](https://guides.emberjs.com/v2.11.0/tutorial/subroutes/) es [queryParamssal](https://guides.emberjs.com/v2.11.0/routing/query-params/) meg lehet oldani konnyeden. Viszont a kodhalmaz jelentos atrendezesevel is jarna. Ez alapvetoen nem problema, de most eleg nagy az "ossze-visszasag" a frontend kodban. Van olyan route, ahol rendesen, komonenseket hasznalunk, van ahol meg nem... (Pedig ugye a komponenseknek az lenne a lenyege, hogy ujrahasznosithato, konfiguralhato kodkent hasznaljuk oket, amit tobb oldalon is fel tudunk hasznalni.)  A jelenlegi kodra raferne egy nagy refactoralas, es azzal egyutt meg lehetne csinalni. Anelkul en nem vagnek bele. 

Viszont mivel jelenleg nagyon keves az eroforrasunk, igy nem hiszem, hogy erre az elkovetkezendo hetekben lesz idonk.

**Comment by jmarton** [comment]
a #121 korrekt megoldása valószínűleg ezen is javít
