### ISSUE TITLE
Éles frontenden username/password login elrejtése

### ISSUE THREAD

**Issue by jmarton** [bme-db-lab/szglab5-frontend#114]
A címtáras bejelentkezés miatt az éles rendszeren nincs szükség a felhasználói név+jelszó alapú bejelentkezésre. Lokális fejlesztő rendszeren azonban szükséges.

Ezért jó lenne egy frontend konfigurációs paraméter, aminek hatására az éles rendszerben a login komponensben csak a címtáras bejelentkezés lehetőség jelenik meg,

**Comment by csutorasr** [comment]
Production build-nel egy env valtozo, true, arra lehetne szurni. Sajnos a kodban ez mindig egy iffel fog feleslegesen jarni, kiveve, ha a ember-cli-ban mar van tree-shaking.

**Comment by lordblendi** [comment]
tree shaking: Ember 3.0-hoz mar WIP, hamarosan belekerul az ember-cli-ba: https://github.com/kellyselden/ember-cli-tree-shaker
