### ISSUE TITLE
Cleartext jelszó API válaszban

### ISSUE THREAD

**Issue by dnet** [bme-db-lab/szglab5-frontend#117]
Az `/api/events` API végponttól kapott válaszban többek között szerepel az érintett felhasználók (oktató, hallgató) kezdeti jelszava. A 2018-ban alkalmazott címtáras belépés miatt ezt meg sem változtatják, így az `initPassword` mezőben lévő jelszóval bárki beléphet (vö. #114). Kipróbáltam a saját felhasználómmal (demonstrátor) és egy hallgatóéval, működött.

A válaszban egyébként szerepelnek hash-selt jelszavak is a `password` mezőben is, ezeket egyrészt nem ártana szintén nem kiküldeni, másrészt kérdés, hogy miért léteznek egyáltalán a táblákban, ha a címtáras belépés engedélyezett csak, hiszen így ez gyakorlatilag egy „backdoor” azok számára, akik ismerik ezt a jelszót.

**Comment by jmarton** [comment]
hotfix: töröltem az `initPassword` mező tartalmát az adatbázisból. Köszönöm, hogy jelezted, @dnet!

**Comment by jmarton** [comment]
@Kisfejes fyi.

**Comment by dnet** [comment]
Közben rájöttem, hogy van backend projekt is, és ez meg a másik 2 security issue is inkább oda való. Migráljátok nyugodtan, vagy hivatkozzátok onnan, ha gondoljátok. Sorry, my bad.

**Comment by Kisfejes** [comment]
Igen, backend issue lesz, mar dolgozok rajta. Annyi a "szerencse", hogy hallgatok nem fertek hozza a vegponthoz.

**Comment by lordblendi** [comment]
> Közben rájöttem, hogy van backend projekt is, és ez meg a másik 2 security issue is inkább oda való. Migráljátok nyugodtan, vagy hivatkozzátok onnan, ha gondoljátok. Sorry, my bad.

Nem gond, kiirtam mindet backendre. Ezt is, meg a tobbit is zarom.
