### ISSUE TITLE
Nyelv egysegesitese

### ISSUE THREAD

**Issue by lordblendi** [bme-db-lab/szglab5-frontend#12]
A hallgatok altal erintett teruletek a kulfoldi hallgatok miatt legyen angol, a tobbi helyen viszont legyen magyar a felulet nyelve.

**Comment by csutorasr** [comment]
Idaig azt a dontest hoztuk meg, hogy mindenhol angol, kiveve a hallgatoi felulet.

**Comment by lordblendi** [comment]
A hallgatoi felulet miert nem angol? Hisz pont ott vannak a magyarul nem tudo felhasznalok. Szerintem a hallgatoknal angolt kellene hasznalni.

Mivel az oktatoi garda minden tagja magyarul tud, ezert ott celszerubb a magyar, de ez nem letfontossagu.

**Comment by Kisfejes** [comment]
Én támogatnám a mindenhol angolt, a backend is angol hibaüzeneteket ir.

**Comment by lordblendi** [comment]
Akkor legyen teljesen angol.

**Comment by lordblendi** [comment]
@csutorasr Akkor teljesen angollal ez az issue lezarhato vegul, nem?

**Comment by csutorasr** [comment]
A menu-helper nem. A tobbi mar kesz. De azert nezd at te is.

**Comment by lordblendi** [comment]
Mivel az oktatoi garda minden tagja magyar, ezert az oktatoi feluletet magyarra fogjuk valtoztatni.

**Comment by lordblendi** [comment]
Az elmult commitokban igyekeztem az oktatoi oldal minden reszet magyarositani. Ami angol oldal: barmi, amit a hallgato lat / ami kozos a hallgatoval.
Ezenkivul meg javitottam par angol kifejezest is.
