### ISSUE TITLE
Nagy méretű, redundáns válaszokat adó kérések /api/events végpontok felé

### ISSUE THREAD

**Issue by dnet** [bme-db-lab/szglab5-frontend#121]
- [ ] `/api/evets` listázás
 - [ ] `/api/eventTemplates` listázás

Amikor demonstrátorként kiválasztok egy labort, először lekéri az `/api/events?filter[eventTemplateId]=X` végpontról az adatokat, amire érkezik egy 85 kB méretű JSON (https://github.com/bme-db-lab/szglab5-backend/commit/f795fc66a179be557220db77db1ccd2e556aaffd előtt volt ez 110 kB is). Ezt követően **hallgatónként** lekéri az `/api/events/<id>` végpontról **ugyanezeket az adatokat**, esetemben 20 kéréssel összességében még >80 kB JSON-t letöltve.

Kérdésem: szükséges a backendet ennek összeszedésével és szerializálásával, az UA-t ugyanennek parse-olásával kétszer terhelni?

Ezen kívül talán érdemes az `attributes` részeit a további (`Users`-en kívüli, lásd fenti commit) entitáshalmazoknál is csökkenteni, például kérdéses, hogy szüksége van-e a frontendnek a `filePath` attribútumra (és még adatot is leakel a szerver működéséről), de ez ismét inkább backend issue.

**Comment by jmarton** [comment]
Tesztelendő, hogy a fronetnden az event listázó hívások számítanak-e includeModel-ekre, vagy mindig azt a `/api/evetnt/<id>` végpontről kéri le részletezve. Ez utóbbi esetben a listázó hívásból az include models egy része vagy egésze megspórolható:

https://github.com/bme-db-lab/szglab5-backend/blob/f70e91b6c1c61108cb2806122516fb0cb9512cc4/endpoints/events/list.js#L149

**Comment by jmarton** [comment]
Másik érintett hely:
https://github.com/bme-db-lab/szglab5-backend/blob/f70e91b6c1c61108cb2806122516fb0cb9512cc4/endpoints/eventTemplates/list.js#L65

Valószínűleg van több érintett hely is, a kérdés az, hoyg egy szisztematikus átnézés mekkora meló.
