### ISSUE TITLE
Shibboleth authentikáció esetén a token restore alkalmával ellenőrizni kellene a token érvényességét

### ISSUE THREAD

**Issue by jmarton** [bme-db-lab/szglab5-frontend#122]
Jó lenne, ha a Shibboleth authentikátor ellenőrizné a token érvényességét, mielőtt a session restore-t az alábbi kódrészlet jóváhagyja.

https://github.com/bme-db-lab/szglab5-frontend/blob/a6d68c9bfc806cfd521de7b3b26880cf1e5a6fcc/app/authenticators/shibboleth.js#L12-L22

A feladat nice-to-have, mert legrosszabb esetben egy következő lépcsőnél mondja majd azt a BE, hogy lejárt a token.

@Kisfejes van token ellenőrző végpont?

**Comment by jmarton** [comment]
Azt gondoljuk @lordblendi-vel egyetértésben, hogy ez lehet a mai hallgatói login probléma mögött (HTTP 403 válasz a backendtől).

Febr.27. 16:40 után febr.28. 13:54 a logban az első bejegyzés az érintett hallgatóra, a levelét pedig 13:38-kor írta, ami alátámasztani látszik a feltételezést.

@Kisfejes, van token ellenőrző API végpont?

@gajdos FYI.

**Comment by Kisfejes** [comment]
Van token ellenorzo vegpont: 
POST /auth/verify-token
application/json
{
  "token": $TOKEN_STRING
}

**Comment by jmarton** [comment]
Ez elkészült a c8df70c029c5acca4983b4cb2c5de091eb8b3c44 commitban, azóta nem találkoztunk erre emlékeztető hibával, ezért lezárom.
