### ISSUE TITLE
Beadandó ill. laborjegy mező csak egész számot fogadjon el

### ISSUE THREAD

**Issue by jmarton** [bme-db-lab/szglab5-frontend#126]
@tsvetlin javaslata bme-db-lab/szglab5-backend#106 kapcsán:

A beadandó ill. laborjegy input fieldbe csak egész számokat lehessen beírni.

**Comment by lordblendi** [comment]
Erdekesseg: a html5 input type="number" csak nem enged szamonkon kivul mast beirni (illetve par irasjelet igen). De nem lehet egesz szamra allitani. Ha adok neki min/max erteket, akkor csak a jobb oldali valtoval (nyilak az input jobb oldalan), csak azt tudom valtoztatni.

Ha teljesen biztos validalast akarunk, akkor javascripttel tudom ellenorizni a beirt szoveget (regex). Melyik legyen @jmarton?

**Comment by jmarton** [comment]
@lordblendi legyen regexp (`^[1-5]$`). Jól sejtem, hogy a validáló kódot rákötni is van valami modern, 1-soros megoldás.
