### ISSUE TITLE
Javitandok rendezese, szinezese

### ISSUE THREAD

**Issue by gajdos** [bme-db-lab/szglab5-frontend#137]
A javitok jelenleg nem abban a sorrendben latjak a javitandoikat, ahogy javitani/ill. javitasra kivalasztani illene oket (a legregebbieket kellene eloszor kijavitani), ill. nem jelzi nekik semmi, hogy egy jkv. mar regota (pl. 3 napnal regebben) var javitasra. Lsz. tegyetek ezeket forditott idorendi sorrendbe mind a Javitando kivalasztasa, mind a Javitas es kijavitott feladatok menupont alatt megjeleno listak eseten.  Ezen kivul a 3 napnal regebben varakozo jkv-eket pirossal kellene kiirni, ami pedig 5 napnal is regebben varakozik, azok meg villoghatnanak is.

**Comment by lordblendi** [comment]
Szerintem érdemes lenne laboronként lebontani őket, hasonlóan, ahogy a demonstrátoroknál is felbontottuk csoportokra. Laborok sorrendje alapján, lenne akkor ehhez hasonlóan:

ORACLE
- táblázat - 

SQL
- táblázat - 

és így tovább. Egy labor akkor jelenne meg, ha van hozzá javítanivaló feladat.

A szűrőt pedig megtarthatnánk feladattípusokhoz. Alapból mindkettőt beraknánk a táblázatba (külön oszlopban jelezni), és lehetne szűrni, ha valakinek van legalább 2 feladattípusa.

Emellé még a kiemelést pedig természetesen meg lehet csinálni.

Ha ez megfelel, akkor nov 2-án meg tudom csinálni. Előbb sajnos nem érek rá.

**Comment by gajdos** [comment]
Amennyiben jol dekodolom a fentieket, akkor ez meg jobb lenne, de tobb munka aran ;-) Ezert en csak megkoszonni tudom, ha elkeszul.
