### ISSUE TITLE
"Nincs csoportja" esetben üres oldal helyett üzenet megjelenítése

### ISSUE THREAD

**Issue by jmarton** [bme-db-lab/szglab5-frontend#139]
Kpacsolódó #133 

Ha egy demonstrátor helyettesítést kér, akkor a csoportja az adott laborra átkerül másik laborvezetőhöz. Ekkor az eredeti laborvezetőnél üresen jelenik meg az adott labor listája. Jó lenne, ha ilyenkor a "nincs csoportja" üzenet jelenne meg.

A jelenlegi helyzet az eredeti laborvezetőnél, miután a sql3 laboralkalma átadásra került másik laborvezetőhöz:

![kép](https://user-images.githubusercontent.com/10688599/99152404-ce707a00-26a1-11eb-9522-bc0e7dd28aff.png)

**Comment by lordblendi** [comment]
Zárható @jmarton ?
