### ISSUE TITLE
Csoportcserélt hallgató megjelenítése a laborvezetőnél az eredeti időpontban

### ISSUE THREAD

**Issue by jmarton** [bme-db-lab/szglab5-frontend#140]
Csoportcsere történt az egyik hallgató egyik laborjára vonatkozóan úgy, de az eredeti és az új laborvezető ugyanaz.

A hallgató az új időpontot látja, de a laborvezetőnél - félrevezető módon - az eredeti időpontnál jelenik meg a hallgató.

**Comment by lordblendi** [comment]
Zárható @jmarton ?
