### ISSUE TITLE
Feltoltes hiba

### ISSUE THREAD

**Issue by lordblendi** [bme-db-lab/szglab5-frontend#16]
Mar ketten jeleztek, hogy a feltoltes nem mukodik, pl Kanyo Krisztian is 2017. szept. 13., Sze, 14:26.

Egyelore logot nem kaptunk

**Comment by csutorasr** [comment]
Az dev-admin felületen kipróbáltuk és működött a frissítés.

**Comment by lordblendi** [comment]
Logot kell kerni a hallgatoktol, anelkul nem fog kiderulni, hogy mi a hiba.

**Comment by csutorasr** [comment]
Tobb emberrel beszeltem. Az lehetetlen, hogy 300 ember tud feltolteni es 1 nem.

**Comment by lordblendi** [comment]
Akkor egyelore zard kerlek
