### ISSUE TITLE
Admin - jegyzokonyv ujrafeltoltese

### ISSUE THREAD

**Issue by lordblendi** [bme-db-lab/szglab5-frontend#17]
Az admin tudjon jegyzokonyvet ujra feltolteni hallgato helyett. Specifikalhassa az idopontot is hozza. Ez ki lett veve a funkcionalis specifikaciobol, amikor GIT only-ra terveztuk a projektet.

**Comment by csutorasr** [comment]
Csak az admin? Ne inkabb a demonstrator? Szerintem ezzel ugysem az admint keresik meg.

**Comment by lordblendi** [comment]
Eddig csak az admin tudott. Szerintem jo lenne, ha az maradna. @jmarton?
