### ISSUE TITLE
Student Oldal  - jkv kesve feltoltese

### ISSUE THREAD

**Issue by lordblendi** [bme-db-lab/szglab5-frontend#20]
Kesve feltoltes biztositasa a hallgatonak.

---
A https://github.com/bme-db-lab/szglab5-frontend/issues/17 bughoz kapcsolodoan par kerdes:
 
A regi rendszerben a kovetkezo volt az ujrafeltoltes menete:

Hallgatoknal hatarido lejarta utan:
- ha nem ad le jegyzokonyvet hataridoig, akkor hatarido utan 1 lehetosege van feltolteni (a megfelelo szankciokkal). Ilyenkor jelezni kell a hallgatonak, hogy hany oraja kesik a beadassal.
- ha adott le jegyzokonyvet, akkor a rendszerben o nem tudja feltolteni az uj valtozatot, engedellyel kerhet uj feltoltest oktatokon keresztul. Ilyenkor elkuldi a demonstratornak emailben, az eljuttatja egy adminhoz, es az admin pedig megcsinalja a feltoltest.

Hatarido elott termeszetesen tovabbra is korlatlan feltoltesi lehetoseget kell biztositani.

Mit tamogat jelenleg ezek kozul a rendszert? Azt tudom, hogy az admin altali feltoltes nincs benne, errol szol a https://github.com/bme-db-lab/szglab5-frontend/issues/17 bug is.

**Comment by csutorasr** [comment]
Ha [itt](https://github.com/bme-db-lab/szglab5-frontend/blob/master/app/models/deliverable.js#L22-L24) a kulonbseget nem nullara ellenorizzuk, akkor megjelenik a feltoltes gomb.

Masik mukodes lehet, hogy ez marad igy, es az `isOver` eltelese utan is marad a feltoltes, csak mutatjuk, hogy az ido letelt, esetleg a hataridot kiirjuk.

**Comment by lordblendi** [comment]
Szerintem keses soran jelezni lehetne a hallgato szamara, hogy hany orat kesett.  Ld. https://github.com/bme-db-lab/szglab5-frontend/issues/38

Van arra lehetoseg, hogy ellenorizd, hogy volt-e mar feltoltes? Valami true/false ertekben @Kisfejes ?

Mert akkor lehetne az, hogyha  `voltFeltoltes == true`, akkor `isOver == true` utan eltunik a feltoltes gomb. 
Ha meg nem `voltFeltoltes == false` es `isOver == true`, akkor pedig amig nincs feltoltes, addig jelenjen meg a feltoltes gomb.

**Comment by csutorasr** [comment]
Van ra, a neve `uploaded`.
