### ISSUE TITLE
Evaluator - tablazat

### ISSUE THREAD

**Issue by lordblendi** [bme-db-lab/szglab5-frontend#24]
A lefoglalos tablazatban jelenjen meg:
- hallgato neve
- hallgato neptunja
- beadas ideje
- beadas hatarideje
- feladattipus - pl.: 22-AUTO
- labor - pl oracle1

Extra informacio a tobbiben:
- jegy
- imsc pont
- javito neve

**Comment by csutorasr** [comment]
Az eztra informaciot nem tudom hova gondoltad, remelem masik issuekban benne van.

Az issue tartalmat megcsinaltam.

**Comment by lordblendi** [comment]
Extra info: minden masik tablazat, ahol mr van jegye a hallgatonak: 
- grading
- graded (vagy mi a neve)

Nincs masik issue, kerlek ird ki

**Comment by csutorasr** [comment]
Mi a minden masik tablazat?

**Comment by lordblendi** [comment]
Evaluator - amikor nezegeted a lefoglalt hallgatok tablazatat
evaluator- amikor nezegeted a veglegesitett hazik tablazatat

**Comment by csutorasr** [comment]
Kikerestem, ezeket mar mutatja
