### ISSUE TITLE
Evaluator - grading

### ISSUE THREAD

**Issue by lordblendi** [bme-db-lab/szglab5-frontend#29]
Ne legyen power-selectes szures. Jelenjen meg egymas alatt a ket tablazat, labellel, hogy melyik micsoda.

**Comment by csutorasr** [comment]
A pagination ugy nem igazan oldhato meg a jelenlegivel. Uj pagination megoldhatja, kulonben 200 kijavitott deliverable lenne ott, ami perfomanciaban es atlathatosagban sem jo.

**Comment by lordblendi** [comment]
Grading eseten az eppen ertekeles alatt levoket kellene latni, nem? Ketlem,
hogy ott 200-nak kellene lennie.

**Comment by csutorasr** [comment]
A javito nevet is kiirja.
