### ISSUE TITLE
settings

### ISSUE THREAD

**Issue by bkopy** [bme-db-lab/szglab5-frontend#3]
1. nincs kukac a mailcimben nem szól
2. update-re nincs semmilyen üzenet
3. nem cserelodik a jelszo
4. a legutolso menuhoz lep vissza logout utan

**Comment by Kisfejes** [comment]
A jelszó cserét jelenleg a backend nem támogatja, dolgozok rajta

**Comment by csutorasr** [comment]
> a legutolso menuhoz lep vissza logout utan
Ezt arra erted, hogy ha ujra belepsz? vagy nem a bejelentkezest hozza be megint?

**Comment by bkopy** [comment]
@csutorasr logout-login utan. sry

**Comment by csutorasr** [comment]
Kukacra meg mindig nem szol, tobbi javitva.
