### ISSUE TITLE
Student oldal - laborvezeto neve es email cime nem jelenik meg

### ISSUE THREAD

**Issue by lordblendi** [bme-db-lab/szglab5-frontend#36]
![image](https://user-images.githubusercontent.com/1140416/30492322-65c2efec-9a40-11e7-8405-e026d484506d.png)

**Comment by csutorasr** [comment]
Legfrissebb frontenddel es backenddel nekem kihozza. Hogyan tudtad reprodukalni?

**Comment by lordblendi** [comment]
Mostmar jonak tunik. Tegnap, amikor kiirtam az issuet, megszemelyesitettem egy hallgatot, akkor nem jelent meg.
