### ISSUE TITLE
Imsc pont

### ISSUE THREAD

**Issue by lordblendi** [bme-db-lab/szglab5-frontend#39]
Imsc pont nem kulon szamit beugrora/laborra/jkv-re, hanem egy egesz laborra es az ertekelo adja a beadott anyagok javitasa soran. Egyetlen mezore van szukseg az ertekeloi oldalon.

Tehat Bela kap 2 imsc pontot az oracle1 laborra Javito1-tol.

@Kisfejes Ez teged is erdekelhet.

**Comment by csutorasr** [comment]
Szoval a deliverable-n nincs imsc pont csak az eventen.

**Comment by lordblendi** [comment]
Igen.

**Comment by jmarton** [comment]
Az igazi megoldás valahol a régi és a módosított állapot között van.

A javító az iMSc pontot a deliverable példányra adja. Szebb lenne, ha nem jelenne meg a beugrónál az iMSc pont mező. Mégszebb az lenne, ha a DeliverableTemplate egy mezője szabályozná, hogy mihez kell imsc pont, és mihez nem.

Ha megjelenik, akkor maradjon null, ne pedig 0, ha nem töltötte ki az ember (feltéve, hogy ez máshol nem okoz gondot).

A laborvezető az event példányra fogja kitölteni az iMSc pontot, amihez figyelembe veszi a deliverable példányra a javítótól kapott értékelést. Ebben hasonlít a munkafolyamat a jegy és a szöveges értékelésre is.

**Comment by csutorasr** [comment]
Nincs input mezo.
