### ISSUE TITLE
Button z index and color

### ISSUE THREAD

**Issue by bkopy** [bme-db-lab/szglab5-frontend#4]
![image](https://cloud.githubusercontent.com/assets/6282280/26198665/352e7388-3bc7-11e7-8617-707928064381.png)

lesd meg a button overlay-t.
köszi

**Comment by csutorasr** [comment]
Szandekos, mert ha nincs, akkor a fogaskerekek miatt olvashatatlan.

De errol majd meg kesobb vitazhatunk, addig is itt hagyom az issuet.

**Comment by lordblendi** [comment]
Valoszinuleg a megfelelo font weight-el meg lehetne oldalni szerintem. Az alap designal sem volt kulon hatter a gombnal, megis olvashatoak voltak a feliratok.

**Comment by csutorasr** [comment]
Az oldal inkabb gyorsan hasznalhato legyen, es minden diak szamara konnyen olvashato, egesz napos faradt szemmel is.
A ne legyenek ott ikonok dologgal is kiegyezek.

Addig is lezarom az ugyet, mert nem hinnem, hogy problemat okoz.

**Comment by lordblendi** [comment]
Vagy vedd ki az ikonokat. Szerintem most ugy is tul sotetek a hatterhez
kepest. A regi verzioban nem voltak ennyire sotetek
Robin Csutorás <notifications@github.com> (időpont: 2017. aug. 18., P,
20:56) ezt írta:

**Comment by csutorasr** [comment]
Szinsematol is fugg, hogy mennyire sotetek.
