### ISSUE TITLE
User szures - pagination talalatok szama

### ISSUE THREAD

**Issue by lordblendi** [bme-db-lab/szglab5-frontend#40]
- legyen tobb, mint 10 a talalatok szama. En minimum 20 talalat, mert 10 nagyon keves.

**Comment by csutorasr** [comment]
A menuponttol fugg, de a pagination azert van, mert anelkul lassu a program. Inkabb kattintson megegyet, vagy szurjon jobban, mint hogy lassu legyen.

**Comment by lordblendi** [comment]
Sandor keresere ezt megnoveltem. Nalam lokalisan tesztelve a teljes eles adatbazis masolataval nem volt gond ebbol. Ha megis az lesz, akkor revert.
