### ISSUE TITLE
Default oldal bejelentkezes utan

### ISSUE THREAD

**Issue by lordblendi** [bme-db-lab/szglab5-frontend#47]
1. Student eseten: labor, az aktualis labor kivalasztasaval
2. Admin eseten user kereses
3. Evaluator eseten: corrector oldal
4. Demonstrator eseten Demonstrator oldal

Ha valaki tobb joggal is rendelkezik:

Admin > Demonstrator > Evaluator

**Comment by csutorasr** [comment]
Az ember-simple-auth erre nem ad lehetoseget. Oda kell figyelni, hogy az atiranyitasok miatt (#54) ezt majd tobb helyen is at kell irni.

(Az evaluator legyen corrector.)

**Comment by lordblendi** [comment]
Akkor halasszuk el, egyelore maradjon igy. U

**Comment by lordblendi** [comment]
Az evaluator az angolul ertekelot jelent, aki a beadott munka minoseget,
tartalmat ertekeli. Ezzel szemben a corrector meg a nyelvtani
helytelensegeket (pl ujsagnal), illetve egyeb hibakat emeli csak ki.

A javitok nem csak a hibakat huzzak ala a beadott munkaban, hanem a munka
minoseget ertekelik, hogy az eleri-e az altalunk elvart (mernoki) szintet.
Ezert irnak ertekelest, hogy mi miert nem jo, es nem csak levonogatjak a
pontokat.

A ketto nem egyenlo, ezert lett a projekt elejen az Evaluator kivalasztva,
amely maradjon is igy.
