### ISSUE TITLE
Több beadandó fájl kezelése egy laborhoz

### ISSUE THREAD

**Issue by jmarton** [bme-db-lab/szglab5-frontend#5]
Egy Event példányhoz több FileDeliverable példány is tartozhat (pl. jegyzőkönyv, SQL kód), ami a gyakorlatban azt jelenti, hogy több fájl feltöltését kell támogatni, és a feltöltések adatait több FileDeliverable-re kell megmutatni.

Részleteket @Kisfejes is ismeri.

**Comment by csutorasr** [comment]
Ez már működik frontendről, ha a backend kezeli és kapok hozzá majd nevet
is, nem csak típust. (Valószínűleg szükség lesz egy név mezőre a
deliverables-ben)

2017. aug. 13. du. 6:19 ezt írta ("József Marton" <notifications@github.com

**Comment by csutorasr** [comment]
A vegleges megoldas az lett, hogy tobb deliverables tartozik minden eventhez, es ezekhez kulon-kulon lehet fajlokat feltolteni. A fajlokat kulon tudjak a javitok lefoglalni.
