### ISSUE TITLE
Design - favicon

### ISSUE THREAD

**Issue by lordblendi** [bme-db-lab/szglab5-frontend#51]
Favicon feketere frissitese.

**Comment by csutorasr** [comment]
Az nem jo, azert feher fekete kerettel, mert ha a bongeszoben sotet tema van, mint akar nekem is, akkor semmi sem latszik az ikonbol.

**Comment by lordblendi** [comment]
Feher hatteren meg ez nem tul jo szerintem. Majd esetleg talaljunk ki valami mast.

![screenshot from 2017-09-25 10-35-20](https://user-images.githubusercontent.com/1140416/30799515-5faaa718-a1dd-11e7-8afc-ba20cc2c9ec4.png)

**Comment by csutorasr** [comment]
Legyen vastagabb a keret. Svg-t ki lehet menteni, vastagabb kerettel, ico-ban konvertálod és rész.
