### ISSUE TITLE
Hallgato atadasa masik csoportba

### ISSUE THREAD

**Issue by lordblendi** [bme-db-lab/szglab5-frontend#53]
Demonstratornal szukseges a megvalositas.

A kivalaszthato listaban:
 csoport neve + meres ideje latszodjon

@jmarton: Kell arra szures, hogy egy hallgato oracle1-es laborja csak oracle1 meresre legyen atadhato?

**Comment by jmarton** [comment]
Kapcsolódik: bme-db-lab/szglab5-backend#61

Mivel CLI felület van rá, annak a leutánozása tűnik a leghatékonyabbnak. Az tudja, hogy csak exerciseCategory-n belül hajlandó áthelyezni. Íme egy párbeszéd a cli-vel:

```
? Users's Neptun AAAAAA
Current student group is: v23-6
? Select event template Labor - 1 - oracle1
? New student group v22-5
```

**Comment by jmarton** [comment]
Closed in #125
