### ISSUE TITLE
Akep a főoldalra irányít

### ISSUE THREAD

**Issue by lordblendi** [bme-db-lab/szglab5-frontend#54]
Hiba bejelentese Udvari Tibortol:

> Üdv!
> 
> Szerintem ez már jelentve lett, de biztonság kedvéért írok:
> Ha egy értékelendő hallgatónál az  Akep gombra kattintok, akkor
>  - elkezd tölteni, 
>  - átirányít egy nem biztonságos kapcsolatú oldalra, 
>  - megjelenik egy piros csík az oldal tetején 100 % szélességben (mintha egy szövegdoboz lenne, csak üzenet nélkül), 
>   - majd átirányít a Hírek oldalra.
> 
> URL a folyamat végén: https://fecske.db.bme.hu/?redirect=https%253A%252F%252Fertekelo-dev.db.bme.hu%252FAKEPTest%252Fapplication%253Ftarget%253Dhttps%25253A%25252F%25252Fertekelo-dev.db.bme.hu%25252F%252523AKEPView%25252FJG0SS6%25252Foracle1#/news
> 
> 
> Üdv,
> Tibor

----

Megoldas @nyikesda levele alapjan:

> Sziasztok!
> 
> Azt látom, hogy az AKÉP gombra nem az lett téve linknek, amit a skypon küldtem Márknak. 
> Illetve természetesen ez is jó linknek és jobb is ha ez maradna, csak akkor, amit visszairányít az AKÉP az oldalatokra azt kéne lekezelni (az alapján amit korábbiakban írtam):
> ilyet kaptok vissza pl: https://fecske.db.bme.hu/#/login?redirect=https%3A%2F%2Fertekelo-dev.db.bme.hu%2FAKEPTest%2Fapplication%3Ftarget%3Dhttps%253A%252F%252Fertekelo-dev.db.bme.hu%252F%2523AKEPView%252FR3ABMN%252Foracle1
> 
> A redirect query paramétert kell egyszer URL decodolni és hozzáfűzni a ?token=<user token>-t és redirectolni az így képződött címre, ha a felhasználó sikeresen belépett (vagy már belépve volt).
> Köszönettel:
> Dani

**Comment by csutorasr** [comment]
@nyikesda Ebben 2 kerdojel is van.

Szoval osszefoglalva:

1. Csinalok egy linket: `https://ertekelo-dev.db.bme.hu/#AKEPView/{neptun}/{feladat}` ez legyen `{ALink}` kesobbiekben.
2. Ebbol csinalok egy masik linket: `https://ertekelo-dev.db.bme.hu/AKEPTest/application?target={ALink}` ez legyen `{BLink}` kesobbiekben.
3. A frontendre kirakando link a `: https://fecske.db.bme.hu/#/login?redirect={BLink}`

Ha megerosited, akkor igy implementaljuk.

**Comment by nyikesda** [comment]
@csutorasr kicsit félreértetted, vagy én nem írtam kellő pontossággal, remélem most sikerül pontosan leírnom.
Nem csak az értékelő felület kérne engedélyt a laboradmintól, hanem van más alkalmazása is az AKÉP-nek, ezért szükséges hogy a laboradmin felület login route-ja képes legyen azt lekezelni, hogy ha jön egy olyan url, hogy  `https://fecske.db.bme.hu/#/login?redirect=X`
(tehát volt benne redirect query paraméter) akkor:
- amennyiben be volt lépve a felhasználó: 
```js
window.location.replace(`${decodeURIComponent(X)}?token=${userToken}`);
```
- amennyiben nem volt belépve felhasználó:
akkor kéri a felhasználótól a belépést (ahogy eddig is) és ha az sikeres, akkor a fenti js kód jöhet erre az esetre is

A gombon lévő linket nem kell így megváltoztatni, illetve ha annak a megváltoztatásával élnénk, akkor is előbb utóbb szükséges lenne a most js-kódban leírt funkció, hiszen ha valaki az AKÉP felületéről indul ki bármelyik alkalmazásából, akkor az AKÉP-nek engedélyt kell kérnie a ti alkalmazásotoktól, hogy a birtokában lévő tartalmat jogosult-e megtekinteni a bármelyik oldalára látogatott illető.

**Comment by csutorasr** [comment]
Igy mar ertem, koszonom, megprobalkozom vele.

**Comment by nyikesda** [comment]
En koszonom. Tokeletesen mukodik
