### ISSUE TITLE
Design - ertekeloi oldal

### ISSUE THREAD

**Issue by lordblendi** [bme-db-lab/szglab5-frontend#56]
Azt a visszajelzest kaptam, hogy a gradingnel nem egyertelmu, hogy ott van egy szuro, ezert a javitok "haszontalannak" erzik a menupontot

Labelt odarakni, es a power selectet rendberakni, hogy latszodjon a lefele nyil es a a teljes szoveg.

Todo: tenyleg el kene gondolkodni, hogy van-e ott ertelme a szuronek, es nem lehetne-e okosabban megoldani, laborra valo szuressel.

**Comment by csutorasr** [comment]
A laboronkénti szűrés tetszik, de akkor a table-component-hez egy
`highlight` attribútummal átadni, hogy milyen igaz/hamis értékre adjon
hozzá egy highlight classt.

**Comment by lordblendi** [comment]
Ja azon kivul, hogy paros/paratlanadik sor mas szinu, akkor az "elkezdte-e javitani" meg ilyesmire adjunk meg extra szint? Ok. 


Az embernek van erre egy jo megoldasa: https://guides.emberjs.com/v2.15.0/components/customizing-a-components-element/#toc_customizing-the-element-s-class
Meg lehet adni, hogy mely attributumok erteket tegye ki class-kent. Akar ugy is, hogy "ha valami true, akkor beteszi classnak,hogy XY".

**Comment by csutorasr** [comment]
Hozzaadtam az event valasztasi lehetoseget. Szerintem igy mar hasznalhato.
