### ISSUE TITLE
Evaluator - grading tablazat hianyzo informaciok

### ISSUE THREAD

**Issue by lordblendi** [bme-db-lab/szglab5-frontend#59]
Grading tablazatbol hianyzik:
- feltoltes ideje
- a hatarido
- az Excercise type
- category
- Deliverable 
- imsc.

https://github.com/bme-db-lab/szglab5-frontend/blob/92e583ab34e54ce045bc3ed6462adf31d687d3ca/app/controllers/evaluator.js#L11 -> itt nincs benne. Ez jelenleg a legutolso commit.

https://github.com/bme-db-lab/szglab5-frontend/issues/24 issue masodik fele.

![image](https://user-images.githubusercontent.com/1140416/30521850-eee81568-9bc6-11e7-99c3-8666ba146343.png)

**Comment by csutorasr** [comment]
Nagyon zsufolt lett az oldal.
