### ISSUE TITLE
Student - jegyzokonyv feltoltese mezo nem tunt el

### ISSUE THREAD

**Issue by lordblendi** [bme-db-lab/szglab5-frontend#62]
Megszemelyesitettem egy hallgatot, hogy lassam hogy jelenik meg nala az ertekelesem. Hiaba toltott mar fel hazit es jart le a hatarideje, a jegyzokonyv feltoltese lehetoseg nem tunt el nala.

Ha a hallgato mar toltott fel hazit es lejart a hatarido, akkor kerlek ezt a gombot rejtsuk el.

![image](https://user-images.githubusercontent.com/1140416/30522101-02261bda-9bcb-11e7-9302-3c168dd67ab7.png)

**Comment by csutorasr** [comment]
Úgy volt, hogy ha letelt az idő, akkor még egyet feltölthet. Ha ez így nem
jó, akkor legyen úgy, hogy ha nem töltött még fel, akkor lehessen
feltölteni egyet.

**Comment by lordblendi** [comment]
Igen, elnezest, valoszinuleg felreerthetoen irtam, de az utobbi mondatoddal
megegyezoen gondolkodtam korabban. Tehat:

Ha nem toltott meg fel jegyzokonyvet:
- hatarido elott korlatlan mennyisegben toltogethet fel
- hatarido utan 1 lehetosege van

Ha toltott mar fel jegyzokonyvet:
- hatarido elott korlatlan mennyisegben tolthet fel ujabb verziot
- hatarido utan nincs lehetosege ujabbat felolteni
