### ISSUE TITLE
laboradmin jegyzőkönyv feltöltése

### ISSUE THREAD

**Issue by csutorasr** [bme-db-lab/szglab5-frontend#64]
> A jelenlegi szerintem még mindig nem a legmegfelelőbb. Most azután is fel tudnak tölteni új jegyzőkönyvet, miután a javító értékelte a laborjukat (vagy lefoglalta értékelésre). Ez szerintem továbbra sem egy jó megoldás, főleg ha a fájlok nem verziókezelve kerülnek mentésre.

by: Kanyó Krisztián

A fronend oldali vedelmet is el kell kesziteni.

**Comment by csutorasr** [comment]
Szerintem megoldas lenne, hogy a javitok azokat javitsak utoljara, ahol nincs feltoltve fajl. Azokat konnyu kivegezni es a vegen is eleg, de akkor meg van lehetoseg fajlt feltolteni.

Masik lehetoseg a kesedelmes feltoltes hataridejet megszabni pl max 3 napban, es akkor utana lesz csak lefoglalhato.

@gajdos @jmarton velemenyetek?

**Comment by jmarton** [comment]
@csutorasr ezt biztosan ide akartad írni? Krisztián arról beszél, hogy lefoglalta. Ez azt is jelenti, hogy van fájl, amit értékelnie kell.

A határidő után feltöltést csak akkor szoktunk engedni a hallgatónak, ha nincs eddig beadott munkája, ld. #20 a leírásban. Talán kicsit kusza lett a sok leírás. Ha kell, akkor tisztázzuk slack-en.

A késedelmes feltöltés korlátozásával egyetértek, a 3 nap biztonsággal megfelel.

**Comment by lordblendi** [comment]
https://github.com/bme-db-lab/szglab5-frontend/issues/62 Ez is ide tartozik a https://github.com/bme-db-lab/szglab5-frontend/issues/20 mellett.

A masik topichoz: Es szukseges, hogy az ertekelo irja be az elegtelent, ha nincs feloltve fajl? Szerintem az is jo megoldas lenne, ha az ertekelok csak feltoltott fajlokat latnak hatarido lejarta utan. Ha valahol nincs feloltve a fajl, arra meg a labvez nyugodt szivvel adhatja az egyest, hisz lathatja, hogy nincs feloltve fajl. Es akkor az ertekelok idejet sem raboljuk ezzel (megha nem is olyan sok ido).

**Comment by csutorasr** [comment]
De ha késedelmes a feltöltés, mi meg odaírjuk az 1est, akkor nem lesz
boldog a hallgató.

**Comment by lordblendi** [comment]
Hogy erted, hogy "mi odairjuk az 1-est"? Nem neked, hanem a laborvezetonek
kellene egyest irnia.

Robin Csutorás <notifications@github.com> ezt írta (időpont: 2017. szept.
19., K, 14:24):

**Comment by gajdos** [comment]
En azt tartanam logikusnak, ha a javito valoban csak a szakmai tartalommal foglalkozna. Ha nincs jkv, ne legyen tehat vele dolga. Egyebekben pedig a beerkezett jkv-et mihamarabb kezdhesse javitani, hiszen az lenne a cel, hogy a hallgatok mihamarabb visszacsatolast kaphassanak. Ennek csak a beadasi hatarido lejarta szabjon gatat, az elott ne kezdodjon a javitas, hatha ujabb verziot akar a hallgato feltolteni. A hatarido lejarta utan viszont ilyet mar ne akarjon, akar lehetove teszi a mostani rendszer, akar nem.
A labvez viszont ha latja, hogy lejart a beadasi hatarido es hianyzik a jkv., akkor 12 oraval kesobb mar beirhatja a jelzest a jkv. hianyara (tipikusan egy nullast), hiszen 12 oranal tobb keses eseten amugy is elegtelent er a jkv. Hirtelen nem latom, hogy van-e erdemi kulonbseg a ketto kozott a potlas szempontjabol, szerintem nincs. Csak elvi jelentosege van, hogy ne egyest kapjon az, aki be sem adott semmit.

**Comment by csutorasr** [comment]
Most egy szoveg megjelenik a laborvezetonek, hogy meg tolthet fel a diak munkat.

A 13 oras feltoltesi korlatot beallitsam? 12+1, hogy legyen lehetosege biztosan. Ha a diak mar nem tolthet fel, akkor a labveznel se fogja ezt irni.

**Comment by gajdos** [comment]
Koszi, remek, jo lesz igy.

**Comment by csutorasr** [comment]
Letesztelve 😄 
Fun fact: 
![image](https://user-images.githubusercontent.com/6360699/30709250-e621cdb4-9f01-11e7-8171-c9eb9de97ad8.png)

A backend ehhez meg szukseges. ([issue](https://github.com/bme-db-lab/szglab5-backend/issues/76))
