### ISSUE TITLE
Demonstrator: táblázat rendezése név szerint

### ISSUE THREAD

**Issue by dnet** [bme-db-lab/szglab5-frontend#66]
Mint az alábbi képernyőfotón is látható, nagyon zavaró módon jelenik meg az oktatói nézetben a csoportom névlistája. „Nagyságrendileg” rendezett, mert pl. a **B** az elején, a **P, S, T, W** a végén van, így minden alkalommal első ránézésre úgy érzem, rendezett, aztán rossz helyen keresem benne a közepe tájára eső hallgatókat (**G, J, H, K, K** a sorrend a helyes **G, H, J, K, K** helyett, ráadásul a közös prefixűek között is rossz a sorrend).

Szóval szinte rosszabb, mintha teljesen véletlenszerű lenne, mert folyamatosan összezavar azzal, hogy rossz helyen keresem a hallgató nevét, ami főleg névsor készítéskor és beugró felvitelkor zavar meg.

Ha megoldható, kérlek rendezzétek név szerinti növekvő sorrendben.

![foo](https://user-images.githubusercontent.com/163115/30686658-382f0c82-9eb9-11e7-82a9-02180e0ba051.png)

**Comment by csutorasr** [comment]
A backend seed nem az igazi, nincsenek event templatek, igy tesztelni nem tudtam, de jonak kellene lennie.

Kerlek @Kisfejes nezd meg a di-t, ezt pedig frissitsd be! :)

**Comment by csutorasr** [comment]
Nem ment, elneztem egy par cuccot.

**Comment by dnet** [comment]
👍 Tökéletes, köszönöm!
