### ISSUE TITLE
Hirek listanézet - user get kérés

### ISSUE THREAD

**Issue by Kisfejes** [bme-db-lab/szglab5-frontend#67]
A hireknél ne küldjön get kérést a a hir kiirójára, mert azt szerver 403-al elutasitja. Én azt javaslom, hogy a szükséges attribútumokat includeolom, a hireknél.

Elég ASAP lenne, meghal miatta a js kód, és más hibákat is okoz. (pl utána nem lehet listázni a hireket, csak oldalfrissités után)
![image](https://user-images.githubusercontent.com/6561081/30691070-c5a37244-9ec6-11e7-8588-c71c657299e5.png)

**Comment by csutorasr** [comment]
Ha include-olod, akkor jo lesz. Eleg a nev attributum is ahhoz a felhasznalohoz.

**Comment by Kisfejes** [comment]
fixed
