### ISSUE TITLE
javítási statisztika

### ISSUE THREAD

**Issue by bkopy** [bme-db-lab/szglab5-frontend#68]
> nem sikerult ilyet talalnom, pedig a tapasztalatok szerint nagy szukseg van ra, hiszen ennek alapjan tudom – es kell is... – osztokelni az egyes javitokat a folyamatos javitasra.
> Hasonloan szukseges lenne a laborvezetoi jegy veglegesitesi statisztika is.
SAndor

egy view amiben ha jol értettem az admin meg tudja nézni hogy mennyi javítanivaló van mely feladatokból
backend issue létrehozva api végpont biztosítására.

**Comment by Kisfejes** [comment]
Készül a backend végpont https://github.com/bme-db-lab/szglab5-backend/issues/72, átállitom ASAP-ra, mivel tényleg elég sürgős, mint a javitóknak, mint az adminoknak, hogy képet kapjanak a jegyzőkönyvek állapotáról.

**Comment by Kisfejes** [comment]
Ezzel tudunk haladni? Elég fontos, hogy képet kapjunk az aktuális állásról.

**Comment by lordblendi** [comment]
Szerintem ezt lezartnak tekinthetjuk.
