### ISSUE TITLE
Javito neve és mailcime 

### ISSUE THREAD

**Issue by bkopy** [bme-db-lab/szglab5-frontend#69]
> Nemcsak nekunk, a hallgatoknak is fontos lenne, hogy tudjak, ki javitotta a munkajukat, es meglegyen a lehetoseguk, hogy kapcsolatba lephessenek vele. Erre a celra fel kellene tuntetni a javito mail cimet a javitas mellett, amire egy kattintassal rogton mail-t is kuldhetne neki a hallgato/akarki. Megha nem is hasznaljak tomegesen, az optikaja sokkal jobb lenne az egesz javitasi folyamatnak.
SAndor

**Comment by Kisfejes** [comment]
A hallgatóknál Events/:id végponton include-oltam a Deliverables-hez tartozó Correctort-t,
A javítóknál Deliverables/:id végponton ugyanez
