### ISSUE TITLE
Bejelentkezéskor legyen fókusz a felhasználónév mezőn

### ISSUE THREAD

**Issue by dnet** [bme-db-lab/szglab5-frontend#70]
Amikor a _Bejelentkezés_ linkre kattintok, a fókusz a linken marad, és külön kell a felhasználónév mezőre vinni, ami a böngészőn kívüli jelszómenedzserek és kézi autentikáció esetén egyaránt kényelmetlenebb mint amennyit egy ilyen változtatás igényel. :)

Ha megoldható, a bejelentkező képernyőn a fókusz kerüljön automatikusan a felhasználónév mezőbe.

**Comment by dnet** [comment]
Nekem továbbra sem így működik, pedig az ennél később javított #71 hatását látom, tehát gondolom a kód kinn van a fecske.db.bme.hu-n. Mi lehet a gond?

**Comment by csutorasr** [comment]
Az ember szerint mennie kell. Nalam mukodik is. Milyen bongeszot hasznalsz?

Egyeduli problema, amit eszrevettem, hogy ha tobbszor ugyanaz a nezet jon be, akkor nem lesz aktiv.

**Comment by dnet** [comment]
Mozilla/5.0 (X11; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0

**Comment by dnet** [comment]
most kipróbáltam Chromiummal, azzal valóban működik

**Comment by dnet** [comment]
most kipróbáltam egy tisztább Firefox profillal is, azzal sem megy :(

**Comment by dnet** [comment]
Talán ez lesz az? https://stackoverflow.com/questions/9955398/autofocus-attribute-of-html5-does-not-work-only-in-firefox-when-forminput-ar

> Autofocus is only done before onload has fired; it's meant to be a declarative way of specifying focus on initial page load.

> It works fine with opera/safari/chrome though!

> The spec doesn't define exact behavior for the attribute, so all the implementations involved are actually spec-compliant. The spec does describe what the general idea is, but different browsers interpret what behavior that should lead to differently.

**Comment by csutorasr** [comment]
Sajnos ezzel nem tudok mit kezdeni. Az element id alapjan megkeresheto, de a frameworkon belul kene maradni. Emberjs-hez tudsz esetleg issuet felvenni.

**Comment by dnet** [comment]
[Ez](https://www.npmjs.com/package/ember-autofocus) nem oldaná meg a problémát?

**Comment by dnet** [comment]
Ping? (BTW ez miért closed?)

**Comment by csutorasr** [comment]
Mert nem mentem ra a reopenre.

**Comment by csutorasr** [comment]
A lib-ek behuzasa utan nekem mindig forditasi hibakat dobott a rendszer. Lehet hogy valamit elrontok, ember install-t szoktam hivni. De utana full clearrel se fordul a kod, ha a kommitra visszaallok se. Ilyenkor az egesz repot ujra szoktam huzni.

@lordblendi ha te meg tudod csinalni, akkor kerlek tedd meg.

**Comment by lordblendi** [comment]
@csutorasr Az ember installt meg a dokumentacio sem irja, bower install kellett neki, ahogy a doksi is irja: https://www.npmjs.com/package/ember-autofocus#installing Ez alapjan mondjuk en abban sem vagyok biztos, hogy ez egy hivatalos ember-addon. A src-t pedig nem talalom hozza, sot sajnos az sem tul biztato, hogy 3 eve nem frissitettek.

Egyebkent nalam installacios utani forditasi problema nem jott elo, se node 6-on se node 8-on. De nekem ez az egesz repo ujrahuzas eleg gyanus. Szerintem eleg kellene, hogy legyen, hogy node_modules / bower_components subfolder torlese.

Most ezt talaltam, ez mukodik is nalam linux firefoxon. IE es Safari nincs tesztelve.
https://github.com/amk221/ember-auto-focus

Commit: https://github.com/bme-db-lab/szglab5-frontend/commit/d321c991be2675fe6e9ef49097c2e6b64b19b4f6

@csutorasr kerlek probald ki, hogy most igy jo-e.

**Comment by lordblendi** [comment]
@dnet A hetvegen mindenkeppen frissitjuk a laboradmint. Ha ugy latod majd, hogy megjavult, kerlek zard az issue-t. Ha nem, akkor beszeljunk meg :)

**Comment by dnet** [comment]
Tökéletes lett, köszi! 👍

**Comment by csutorasr** [comment]
@lordblendi A repo ujrahuzas mar csak az idegessegben tortent, de utana jo lett. :D
