### ISSUE TITLE
Admin veglegesites visszavonasa

### ISSUE THREAD

**Issue by csutorasr** [bme-db-lab/szglab5-frontend#77]
A javitoknal hozza lett adva veglegesites gomb. Ha valamit megis javitani kene rekalmacio utan, akkor ezt az admin visszavonhatja.

**Comment by lordblendi** [comment]
Az admin eddig is visszavonhatta a veglegesitest barmire, nem? Vagy ezt kivetted?

**Comment by csutorasr** [comment]
Harom disabled button volt ott.
