### ISSUE TITLE
jegyzőkönyvfeltöltés

### ISSUE THREAD

**Issue by bkopy** [bme-db-lab/szglab5-frontend#78]
> Fel tudnátok készíteni a laboradmin rendszert a 2. laborhoz a NEPTUN-2-CSOPKOD.pdf formátumú jegyzpkönyvek fogadására?
> Illetve az angolos csoportom, akiket Márk nem rég vitt fel, C12A kóddal fognak jegyzőkönyveket feltölteni (NEPTUN-1-C12A.pdf és hasonlók), ezt a csoportkódot tudnátok legalizálni? 
Levi

**Comment by csutorasr** [comment]
Nem igazan ertem mi ennek az ertelme, vagy hogyan es hova kene megoldani.

Mindenki belep es a sajat jegyzokonyvet feltolti.

**Comment by jmarton** [comment]
Ez egy "megszokás-ticket". A régi laboradminba zip-et adtak be, az abban levő fájlneveket pedig egy regexp néha ellenőrizte. Ha jól tudom, ilyen funkció nincs a jelenlegi rendszerben, főleg hogy nem zip-eket adnak be.

Annak lehet értelme, hogy ha a javító letölt egy jegyzőkönyvet, akkor ő strukturált fájlnévvel kapja meg, ne pedig a hallgató eredeti fájlnevével. Ld. még bme-db-lab/szglab5-backend#60

**Comment by jmarton** [comment]
A 2. laborra pdf fogadása az event-hez tartozó deliverable template meghatározására vonatkozó kérés lehet. Ezt a részt érdemes @eroslevi -vel emailben egyeztetni. Nem fejlesztés, csak konfiguráció.

**Comment by Kisfejes** [comment]
A backend issue-val együtt zárom, félreértés volt. Egyébként most már ha valaki letölt egy fájlt akkor NEPTUN_ExerciseCategory_OriginalFileName formátumban kapja
