### ISSUE TITLE
select for grading - exercisetype szures

### ISSUE THREAD

**Issue by csutorasr** [bme-db-lab/szglab5-frontend#79]
A javitok exercise type alapjan is tudjanak szurni.

**Comment by csutorasr** [comment]
Waiting for backend.

**Comment by csutorasr** [comment]
@Kisfejes Zárd le ha készen van.

**Comment by jmarton** [comment]
Kapcsolódik: bme-db-lab/szglab5-main#10

**Comment by jmarton** [comment]
Superseded by #138 
References #100
