### ISSUE TITLE
Evaluator - A student reszleteinel hianyzik a laborvezeto es a hallgato elerhetosege

### ISSUE THREAD

**Issue by lordblendi** [bme-db-lab/szglab5-frontend#80]
Ha gond van a jegyzokonyvvel, akkor elofordulhat, hogy ertesitenunk kell a hallgatot es a laborvezetot. Jelenleg, amikor ertekelunk, nem jelenik meg az informaciok kozott:
- hallgato e-mail cime
- laborvezeto neve
- laborvezeto e-mail cime

**Comment by csutorasr** [comment]
Nem ertem amugy mi alapjan osztasz bugot ide. Szerintem ez nem hiba. Nem hibas a mukodes.

**Comment by lordblendi** [comment]
Rosszra kattintottam
