### ISSUE TITLE
Demonstrátori felületen leadási idő nem látszódik

### ISSUE THREAD

**Issue by bkopy** [bme-db-lab/szglab5-frontend#83]
> A demonstrátori felületen egy-egy hallgató részletezésénél a javító által lezárt értékelés esetén nem jelenik meg a jegyzőkönyv feltöltési dátuma (valamint az összefoglaló táblázatban sem). Így nem tudom figyelembe venni a jegy kialakításánál hogy ki az aki késve adta le a jegyzőkönyvet. Ha jól emlékszem még nem lezárt értékelésű hallgatóknál ez az adat megjelent a részletező oldalon, de azt már sajnos nem látom. Tudnátok valami megoldást találni erre?
Dobai Tamás

**Comment by csutorasr** [comment]
A program [mutatja a kesest es ha kesett, akkor a feltoltes idejet](https://github.com/bme-db-lab/szglab5-frontend/blob/c418a4c84cb8172eb26ec87432e2090bc572e3cb/app/templates/components/demonstrator-student.hbs#L62), mint ahogy azt is, ha [nem toltotte fel](https://github.com/bme-db-lab/szglab5-frontend/blob/c418a4c84cb8172eb26ec87432e2090bc572e3cb/app/templates/components/demonstrator-student.hbs#L66)

@bkopy kerlek jelezd ezt a linket neki.

**Comment by Hunthomas** [comment]
Így világos, csak nem volt egyértelmű az, hogy miért nem jelenik meg default módon a feltöltési idő (azaz akkor is, ha nem késett), véleményem szerint hasznos lenne, ha mindig látnánk, de ez csak "kényelmi" funkció.

**Comment by lordblendi** [comment]
Beraktam mind a hallgato ertekelese nezetbe, mind a csoport tablazatba a feltoltesi idot, fuggetlenul attol, hogy kesett-e a hallgato, ahogy @Hunthomas kerte.
