### ISSUE TITLE
Improvements 

### ISSUE THREAD

**Issue by bkopy** [bme-db-lab/szglab5-frontend#86]
> 1. Jó lenne, ha le lehetne tölteni a hallgató megoldását laborvezetőként is. Ez főleg akkor jó, hogyha jön reklamálni, hogy szerintem itt meg ott miért nem kapta meg a maximális pontszámot. Elég ciki bekérni tőlük a jegyzőkönyvet, főleg, hogy akár ki is javíthatták közben :)
> 2. Laborvezetőként nem látom, hogy ki javította a jegyzőkönyvet, úgyhogy nem is tudok neki szólni. 
> 3. A hallgató laborjának details nézetén nem jelenik meg a név-neptun-feladatsor típushoz az érték.
> 4. Lehet érdemes lenne megfontolni a csoportos jegybevitel lehetőségét. Beugró felvitelekor roppant kényelmetlen egyesével kattingatni a nevekre, felvinni, mentés, vissza, majd újrakezdeni.
Varsányi Márton

**Comment by csutorasr** [comment]
A 3. mikor tortenik? Van valahol bovebb info?

**Comment by lordblendi** [comment]
@varsi94 
Megcsinaltam a kovetkezoket:
- a hallgato minden beadott fajljanak letoltese
- AKEP gomb
- latod mar a javito nevet es emailjet
- en nem lattam olyan hiat, mint amit a 3.-nal leirtal. Lehet, hogy a bejelentes ota ez mar javitva lett.
