### ISSUE TITLE
Feltoltesi idopont modositas

### ISSUE THREAD

**Issue by csutorasr** [bme-db-lab/szglab5-frontend#87]
> 
A 2017.10.10-es labornal (ami meg nem tortent meg) miert jelzi azt, hogy 2017.09.30-kor mar beadta (submitted date), de fajlt nem tudok letolteni?

By @lordblendi

**Comment by csutorasr** [comment]
A problemat az okozza, hogy mindig megjelenik a mezo.

**Comment by csutorasr** [comment]
@lordblendi  dev-re felraktam, mergeld es rakd ki elesbe, ha tetszik.

**Comment by lordblendi** [comment]
Remek, pont ezt a megoldast akartam javasolni. Szerintem igy jonak kell lennie.
