### ISSUE TITLE
Statisztika design

### ISSUE THREAD

**Issue by csutorasr** [bme-db-lab/szglab5-frontend#88]
ha az oldal nem teljes kepernyore van kiteve, akkor a jobb oldali gorditosav nem jelenik meg (Firefox-ban)

By @gajdos

**Comment by lordblendi** [comment]
Ezt tudta valaki reprodukalni? Nalam firefoxon jo.
![image](https://user-images.githubusercontent.com/1140416/31570082-e4205b08-b080-11e7-81c4-0261d01ef076.png)

**Comment by gajdos** [comment]
Remlik, mintha Robin ezt megcsinalta volna...
