### ISSUE TITLE
Evaluator oldal atalakitasa

### ISSUE THREAD

**Issue by lordblendi** [bme-db-lab/szglab5-frontend#9]
**Surgos** 
- A megjeleno tablazatban jelenjen meg a leadas ideje es a hatarido. Enelkul nem lehet eldonteni, hogy mit kell surgosen kijavitani.
- Csak olyan jelenhet meg a tablazatban, aminek a hatarideje mar lejart.
- Vilagosan jelezni kell, hogy mire adtak jegyet es mi van lefoglalva.
- Szures csak akkor jelenjen meg feladatsorra, ha tobb feladatsort javithat az adott javito

**Nagyon ajanlott refactor**
- default ertek: szures nelkul jelenjen meg minden feladatsor.
- Legyen harom almenupont listazasnal: 
  - javithato feladatok: amiket mar valaki lefoglalt, az ne jelenjen meg
    - kattintasra foglalja le
    - csoportos lefoglalas checkboxokkal
  - javitando feladatok: altalad lefoglalt, de nem veglegesitett javitasok
  - kijavitottak: 
    - ket tablazat -  1.altalad javitott 2. masok altal javitott. 
    - Vagy egy nagy tablazat
    - javitok neve legyen feltuntetve

- Ertekelesnel
    - funkcio feloldasra
    - funkcio masik javitonak valo atadasra (akar olyannak is, aki teljesen mas feladatsort javit)

**Comment by csutorasr** [comment]
> Csak olyan jelenhet meg a tablazatban, aminek a hatarideje mar lejart.

Eddig is igy ment.

> Vilagosan jelezni kell, hogy mire adtak jegyet es mi van lefoglalva.

Lefoglalt nem jelenik meg, mert a menupontban lefoglalni lehet. Lefoglaltat nincs ertelme lefoglalni.

> Szures csak akkor jelenjen meg feladatsorra, ha tobb feladatsort javithat az adott javito.

Szeritnem nem problema, ha ott a doboz neki is.

> javithato feladatok: amiket mar valaki lefoglalt, az ne jelenjen meg

Ez mukodik, csak a tobbszoros lefoglalas nem.

> javitando feladatok: altalad lefoglalt, de nem veglegesitett javitasok

Ezt 2 tovabbi reszre is bontottuk, hogy elkezdted-e mar javitani, vagy nem.

Szerintem senkinek nincs koze ahhoz, hogy en "Belanak" milyen jegyet adtam. A tobbiek kilistazasara szerintem nicns szukseg. 

> funkcio feloldasra

Implementalva van ez is.

**Comment by lordblendi** [comment]
> Ezt 2 tovabbi reszre is bontottuk, hogy elkezdted-e mar javitani, vagy nem.
> 
> Szerintem senkinek nincs koze ahhoz, hogy en "Belanak" milyen jegyet adtam. A tobbiek kilistazasara szerintem nicns szukseg.

Erre azert van szukseg, mert a feladatokat egysegesen kell javitani. Javitokent meg lehet nezni, hogy hmm, erre a hibara en ennyit vonnek le, de a tobbiek mennyit vontak le ra? Vagy valamire jar-e levonas, vagy csak megjegyzes.

**Comment by lordblendi** [comment]
A tablazatban nem jelenik meg, hogy milyen feladatsor tartozik a hallgatokhoz, csak Oracl1-bol tudok valogatni jelenleg. Tobb hallgatot latok, mint amennyinek elso nap utan meg kellene, hogy jelenjen a tablazatomban. Ezert megneztem, hogy mi erkezett json-ben. Ez alapjan olyan hallgatokat is megkaptam, akik nem olyan feladatot oldanak meg, mint amit en javitok. 

@csutorasr Lefoglaltam most magamnak egy hallgatot, de nincs opcio a feloldasra.

**Comment by lordblendi** [comment]
Nem jegyzokonyv szerinti szures kellene, hanem feadatsor szerinti: AUTO, HAJO, stb.

**Comment by lordblendi** [comment]
Olyannak nem kell megjelennie, aki nem adott le jkv-et. Annak siman tud a laborvezeto is egyest adni.

**Comment by csutorasr** [comment]
Azért van checkbox a lefoglalásra, mert ha kiválasztasz egy feladatot javításra, akkor javíthatod. Ha a javítás közben kiválasztott feladattal átmész a Select for grading menüre, akkor ki tudod venni a checkboxot.

**Comment by csutorasr** [comment]
Minden feladatnak legyen külön issue-ja. Hogyan zárjam le a felét, és a másik felét tartsam nyitva?

**Comment by lordblendi** [comment]
> Azért van checkbox a lefoglalásra, mert ha kiválasztasz egy feladatot javításra, akkor javíthatod
Nem egeszen ertem ezt a mondatot. Miben kulonbozik egy checkbox click majd save es egy sima egy button-os click?

> Ha a javítás közben kiválasztott feladattal átmész a Select for grading menüre, akkor ki tudod venni a checkboxot.

Ez nem felhasznalobarat mukodes. A bal oldali menunek arra kellene szolgania, hogy kulonbozo menupontok kozott valogass es nem arra, hogy egy adott menupont almenupontnak kulonbozo verzioit elerhesd. 

Legyen egyertelmu a mukodes:
- select for grading: kilistazni az elerhetoeket, es lefoglalni egyet vagy tobbet
- grading: javitani, feloldani vagy atadni masnak

> Minden feladatnak legyen külön issue-ja. Hogyan zárjam le a felét, és a másik felét tartsam nyitva?
Akkor ird ki az issuekat, en nem erek ra ezzel foglalkozni

**Comment by lordblendi** [comment]
Szetosztva:
https://github.com/bme-db-lab/szglab5-frontend/issues/35
https://github.com/bme-db-lab/szglab5-frontend/issues/34
https://github.com/bme-db-lab/szglab5-frontend/issues/33
https://github.com/bme-db-lab/szglab5-frontend/issues/32
https://github.com/bme-db-lab/szglab5-frontend/issues/31
https://github.com/bme-db-lab/szglab5-frontend/issues/30
https://github.com/bme-db-lab/szglab5-frontend/issues/29
https://github.com/bme-db-lab/szglab5-frontend/issues/28
https://github.com/bme-db-lab/szglab5-frontend/issues/27
https://github.com/bme-db-lab/szglab5-frontend/issues/26
https://github.com/bme-db-lab/szglab5-frontend/issues/25
https://github.com/bme-db-lab/szglab5-frontend/issues/24
https://github.com/bme-db-lab/szglab5-frontend/issues/23
https://github.com/bme-db-lab/szglab5-frontend/issues/22
