### ISSUE TITLE
Users List menüpont

### ISSUE THREAD

**Issue by bkopy** [bme-db-lab/szglab5-frontend#90]
> - a hallgatohoz tartozo meresi esemenyek nincsenek ido szerint rendezve, emiatt ossze-vissza jelennek meg
> - kerem, hogy a kulonbozo laboresemenyekhez tartozo kiirasokat valamilyen modon egyertelmuen valasszatok el egymastol, mert most nekem kovethetetlen, hogy mi mihez tartozik.
> - a "submitted date" felirattal kerem, hogy egy sorban alljon a hozza tartozo datum, igy is rengeteg sora van ennek az oldalnak. Hasonloan a "change submitted date" utan alljon, amit modositani kell. A datum mezonek felesleges otszor olyan hosszu keret, mint amilyen hosszu maga  a datum kiirasa.
> - nem vilagos, hogy a Definalize mit csinal, mit von vissza: lehet ertelme visszavonni a jkv feltolteset (es ezzel egy ujat engedni feltolteni (vagy az admin altal feltolteni)), van ertelme visszavonni a javito javitasat a ra javasolt jeggyel, vegul van ertelme kulon visszavonni a laborvezeto altal adott jegyet es a hallgato teljes laborjanak az ertekeleset. Mit csinal most pontosan ez a gomb? Ha mindharmat, vagy a ket utobbit egyszerre, akkor jo lenne szetvalasztani, hiszen mindharom visszavonas 3 kulonbozo szemelyt erint. Ha csak az egyiket, akkor a masik kettot is implementalni kellene, hiszen ezek sajnos mind viszonylag gyakran aktivalt funkciok.
SAndor

**Comment by lordblendi** [comment]
Related issue: https://github.com/bme-db-lab/szglab5-frontend/issues/85

**Comment by lordblendi** [comment]
A https://github.com/bme-db-lab/szglab5-frontend/commit/4fab17dcc0ff4f6999ed861ab3872daec452a843 commitban megcsinaltam a  kinezetet, mar csak a labor veglegesitesenek visszavonasa van hatra. A https://github.com/bme-db-lab/szglab5-frontend/issues/85 -ot (ez is a fentebb elitett mezok designjarol szol) le is zarom igy

**Comment by lordblendi** [comment]
Ua, mint https://github.com/bme-db-lab/szglab5-frontend/issues/94 es https://github.com/bme-db-lab/szglab5-frontend/issues/95 Azok konkretabbak, igy ezt zarom.
